### ISSUE TITLE
Creating 3D models from the code provided

### ISSUE THREAD

**Issue by singhjags** [chuhang/HouseCraft#1]
Hello!

I loved your work. I am trying to do the same using GANs, I can't seem to get output in form of 3D model of the house, can you please let me know how I can do that?

Thanks,

Jagtar

**Comment by chuhang** [comment]
Hi Jagtar,

Thank you for checking out our project! The code is a bit old but let me try to recall as much as I can.

The floorplans we used was labeled with a paint brush. As you can see in
./rent_crawler/goodhouses/house74/floorplan_label1.png
we marked out walls (red), windows (green), doors (blue), and intersection points (yellow).

To read this painted label image, we used the function as in 
./proc_floorplan_label/proc_floorplan_label.m
which will give you a 2D view of the floorplan. For houses with more than one floor, we labeled two images separately so you can read them separately and combine them later.

Inside rent_crawler/goodhouses/houseXX/ there are floorplan_label_data.mat which should have information of how to align e.g. the 1st floor and the 2nd floor. In groundtruth_data.mat under the same folder there are position/height/window size/door size information that we have manually labelled.

The github repo only has house74 as an example due to space limit. To get the full dataset of all SydneyHouse, you can download from http://www.cs.toronto.edu/housecraft/

Hope this helps and looking forward to your GAN results!

- Hang
